# Generated by Django 2.2.6 on 2020-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=254)),
                ('max_date', models.DateTimeField()),
            ],
        ),
    ]
