# Generated by Django 2.2.6 on 2020-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_date',
            field=models.DateField(),
        ),
    ]
