# Generated by Django 3.0.4 on 2020-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200328_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('C', 'Completed'), ('NC', 'Not Completed')], default='NC', max_length=2),
        ),
    ]
